RealEskalate/a2sv-g5-project-phase-starter-project

web/ASTU-web-group-1/astu.web.g1.bank-dash/package-lock.json, web/ASTU-web-group-1/astu.web.g1.bank-dash/package.json, web/ASTU-web-group-1/astu.web.g1.bank-dash/src/app/globals.css, web/ASTU-web-group-1/astu.web.g1.bank-dash/tailwind.config.ts
Added custom colors
Extended font sizes
=> Astu.web.g1.ephrem.2 declare css variables

web/ASTU-web-group-1/astu.web.g1.bank-dash/package-lock.json, web/ASTU-web-group-1/astu.web.g1.bank-dash/package.json, web/ASTU-web-group-1/astu.web.g1.bank-dash/src/components/Form/InputGroup.tsx, web/ASTU-web-group-1/astu.web.g1.bank-dash/src/types/formType.ts
Implemented a reusable InputGroup component.
The component accepts ```id, label, inputType, registerName, register, and placeholder``` as props.
It can be easly Integrated with React Hook Form for form handling using the register function.
=> created: InputGroup

web/AASTU-web-group-4/next-bank/app/(root)/accounts/page.tsx, web/AASTU-web-group-4/next-bank/app/(root)/credit-card/page.tsx, web/AASTU-web-group-4/next-bank/app/(root)/investments/page.tsx, web/AASTU-web-group-4/next-bank/app/(root)/loans/page.tsx, web/AASTU-web-group-4/next-bank/app/(root)/services/page.tsx, web/AASTU-web-group-4/next-bank/app/(root)/setting/page.tsx, web/AASTU-web-group-4/next-bank/app/(root)/transaction/page.tsx, web/AASTU-web-group-4/next-bank/app/(root)/transfer/page.tsx
=> Update the folder structure

web/AASTU-web-group-4/next-bank/app/api/auth/[...nextauth]/Option.ts, web/AASTU-web-group-4/next-bank/app/api/auth/[...nextauth]/Route.ts
created the Option.ts and Router.ts files that are needed for nextAuth to work. Also provided the correct folder path needed as api/auth/[...nextauth] then the two files.
=> created the options and route ts files needed to work with next auth

web/ASTU-web-group-2/banking-dashboard/app/components/navbar/Navbar.tsx, web/ASTU-web-group-2/banking-dashboard/app/components/sidebar/Sidebar.tsx, web/ASTU-web-group-2/banking-dashboard/app/layout.tsx, web/ASTU-web-group-2/banking-dashboard/app/page.tsx
=> layout fixed

web/AASTU-web-group-4/next-bank/app/(auth)/signin/page.tsx, web/AASTU-web-group-4/next-bank/components/Loginform.tsx, web/AASTU-web-group-4/next-bank/package-lock.json, web/AASTU-web-group-4/next-bank/package.json
=> finished sigin ui

backend/ASTU-backend-group-5/cmd/app/main.go
=> project structure initialized

backend/AASTU-backend-group-9/delivery/controller/signup.go
=> :bug: checking

backend/AASTU-backend-group-6/.env, backend/AASTU-backend-group-6/Domain/domain.go, backend/AASTU-backend-group-6/Infrastructure/auth_middleWare.go, backend/AASTU-backend-group-6/Infrastructure/database.go, backend/AASTU-backend-group-6/Infrastructure/jwt_service.go, backend/AASTU-backend-group-6/Infrastructure/lodeEnv.go, backend/AASTU-backend-group-6/Infrastructure/password_service.go, backend/AASTU-backend-group-6/air.toml, backend/AASTU-backend-group-6/bash.sh, backend/AASTU-backend-group-6/cmd/main.go, backend/AASTU-backend-group-6/go.mod, backend/AASTU-backend-group-6/mongo/mongo.go, backend/AASTU-backend-group-6/run.sh
we create the clean folder structure for the project
=> clean folder structure is create

web/AASTU-web-group-2/a2sv-banking-system/app/components/TransactionCard.tsx
made the Transaction Card Component.
=> Transaction Card added

backend/AASTU-backend-group-4/delivery/controller/blog/blog_controller.go
=> Changed folder name

web/AASTU-web-group-4/next-bank/components/BarChart.tsx, web/AASTU-web-group-4/next-bank/components/LineChart.tsx, web/AASTU-web-group-4/next-bank/components/PieChart.tsx
created the bar , line and pie charts with the dummy data that can be found in their respective folder
=> Aastu.web.g4.natnael.dashboard charts

web/AASTU-web-group-6/bankdash/app/(route)/loan/page.tsx, web/AASTU-web-group-6/bankdash/app/(route)/transaction/page.tsx, web/AASTU-web-group-6/bankdash/app/components/Card/VisaCard.tsx, web/AASTU-web-group-6/bankdash/app/components/Loan/LoanTable.tsx, web/AASTU-web-group-6/bankdash/app/components/Transaction/BarGraph.tsx, web/AASTU-web-group-6/bankdash/app/components/Transaction/Recent.tsx, web/AASTU-web-group-6/bankdash/package-lock.json, web/AASTU-web-group-6/bankdash/types/LoanValue.tsx, web/AASTU-web-group-6/bankdash/types/TransactionValue.tsx
Add Loan and Transaction pages
=> Feature: Add Loan and Transaction pages

web/AASTU-web-group-1/aastu.web.g1.bank-dashboard/app/dashboard/_components/Header.tsx, web/AASTU-web-group-1/aastu.web.g1.bank-dashboard/app/dashboard/_components/Sidebar.tsx, web/AASTU-web-group-1/aastu.web.g1.bank-dashboard/app/dashboard/layout.tsx, web/AASTU-web-group-1/aastu.web.g1.bank-dashboard/app/dashboard/setting/component/EditProfile.tsx, web/AASTU-web-group-1/aastu.web.g1.bank-dashboard/app/dashboard/setting/component/Preferences.tsx, web/AASTU-web-group-1/aastu.web.g1.bank-dashboard/app/dashboard/setting/component/Security.tsx, web/AASTU-web-group-1/aastu.web.g1.bank-dashboard/app/dashboard/setting/page.tsx, web/AASTU-web-group-1/aastu.web.g1.bank-dashboard/components/ui/table.tsx, web/AASTU-web-group-1/aastu.web.g1.bank-dashboard/components/ui/tabs.tsx, web/AASTU-web-group-1/aastu.web.g1.bank-dashboard/package-lock.json, web/AASTU-web-group-1/aastu.web.g1.bank-dashboard/package.json
Made minor changes to width to have a consistent UI across team mates' devices.
=> Fixed minor bugs to fix issues across team devices

backend/AASTU-backend-group-8/go.mod
=> initialized the project

backend/AASTU-backend-group-8/domain/blog.go, backend/AASTU-backend-group-8/domain/misc.go, backend/AASTU-backend-group-8/domain/user.go, backend/AASTU-backend-group-8/go.mod, backend/AASTU-backend-group-8/go.sum
=> complete domain

web/ASTU-web-group-2/banking-dashboard/app/components/charts/MyExpenseChart.tsx, web/ASTU-web-group-2/banking-dashboard/app/components/charts/page.tsx
=> added my-expense chart

backend/AASTU-backend-group-5/.gitignore, backend/AASTU-backend-group-5/delivery/main.go, backend/AASTU-backend-group-5/domain/entities.go, backend/AASTU-backend-group-5/domain/user_interface.go
=> [feat]:project setup

web/ASTU-web-group-2/banking-dashboard/app/components/charts/DebitCreditOverviewChart.tsx, web/ASTU-web-group-2/banking-dashboard/app/components/charts/page.tsx
=> Astu.web.g2.wondmeneh.182 debit and credit overview

web/AASTU-web-group-6/bankdash/app/(auth)/login/page.tsx, web/AASTU-web-group-6/bankdash/app/(route)/transaction/page.tsx, web/AASTU-web-group-6/bankdash/app/components/Card/VisaCard.tsx, web/AASTU-web-group-6/bankdash/app/components/Forms/LoginForm.tsx, web/AASTU-web-group-6/bankdash/app/components/Forms/SignUpForm.tsx, web/AASTU-web-group-6/bankdash/app/components/Layout/NavBar.tsx, web/AASTU-web-group-6/bankdash/package-lock.json, web/AASTU-web-group-6/bankdash/package.json, web/AASTU-web-group-6/bankdash/types/UserValue.ts
=> Aastu.web.g6.naod.deployable

backend/ASTU-backend-group-5/cmd/app/main.go, backend/ASTU-backend-group-5/go.mod, backend/ASTU-backend-group-5/go.sum, backend/ASTU-backend-group-5/internal/config/config.go, backend/ASTU-backend-group-5/internal/domain/user.go, backend/ASTU-backend-group-5/internal/http/handlers/user_handlers.go, backend/ASTU-backend-group-5/internal/http/handlers/verification_handlers.go, backend/ASTU-backend-group-5/internal/http/routes/setup_routes.go, backend/ASTU-backend-group-5/internal/http/routes/user_routes.go, backend/ASTU-backend-group-5/internal/http/routes/verification_routes.go, backend/ASTU-backend-group-5/internal/repository/mongodb/user_repo.go, backend/ASTU-backend-group-5/internal/repository/user_repo.go, backend/ASTU-backend-group-5/internal/usecase/user/forgot_password.go, backend/ASTU-backend-group-5/internal/usecase/user/interface.go, backend/ASTU-backend-group-5/internal/usecase/user/login.go, backend/ASTU-backend-group-5/internal/usecase/user/register.go, backend/ASTU-backend-group-5/internal/usecase/user/verify.go, backend/ASTU-backend-group-5/pkg/mongo/client.go
=> auth system completed

web/ASTU-web-group-2/banking-dashboard/app/components/profileSecurity/profileSecurity.tsx
Security component in the profile editing section completed, Along with making it responsive. the layout width depends on the width of the container.
https://github.com/user-attachments/assets/5542d324-90f6-4bc5-afa0-4b62407b4130
=> Security section for the profile completed

backend/ASTU-backend-group-1/config/config.go, backend/ASTU-backend-group-1/delivery/main.go, backend/ASTU-backend-group-1/domain/domain.go, backend/ASTU-backend-group-1/go.mod, backend/ASTU-backend-group-1/repository/blogrespository.go, backend/ASTU-backend-group-1/repository/userrespository.go
* Directories following the clean architecture
* Interfaces for the repositories
* Models for the project
=>  # Creating project structure and files 

backend/ASTU-backend-group-1/repository/user_repository_test.go, backend/ASTU-backend-group-1/repository/userrespository.go
* Writing tests for the repository with mongoifc
* Writing the concrete implementation for the repository methods
* `repository/userrepository.go` for the concrete implementation of the interface
* `repository/user_repository_test.go` for testing the user repository
=> wip: user repository testing and implementing

web/ASTU-web-group-2/banking-dashboard/app/components/charts/YearlyTotalInvestment.tsx, web/ASTU-web-group-2/banking-dashboard/app/components/charts/page.tsx, web/ASTU-web-group-2/banking-dashboard/package-lock.json, web/ASTU-web-group-2/banking-dashboard/package.json
=> add yearly tota; onvestemtnt

web/ASTU-web-group-1/astu.web.g1.bank-dash/src/app/loans/page.tsx, web/ASTU-web-group-1/astu.web.g1.bank-dash/src/components/ActiveLoansOverviewTable/ActiveLoansOverviewTable.tsx, web/ASTU-web-group-1/astu.web.g1.bank-dash/src/components/LoansItems/Loansitem.tsx
Add the Components to the Loan page
Fix the Responsiveness of the components in the loan page
=> Astu.web.g1.chala. loans page

web/AASTU-web-group-4/next-bank/components/AccountBarChart.tsx
created the accounts page bar chart.
=> created the accounts page bar chart

backend/AASTU-backend-group-9/delivery/middleware/auth_middleware.go, backend/AASTU-backend-group-9/delivery/middleware/auth_service.go, backend/AASTU-backend-group-9/domain/token.go, backend/AASTU-backend-group-9/internal/tokenutil/auth_service.go, backend/AASTU-backend-group-9/repository/token_repository.go
=> Aastu.backend.g9.hiwot.authentication

backend/AASTU-backend-group-9/go.mod, backend/AASTU-backend-group-9/go.sum
=> installed mockery

web/ASTU-web-group-2/banking-dashboard/app/components/charts/MonthlyRevenueChart.tsx, web/ASTU-web-group-2/banking-dashboard/app/components/charts/page.tsx
=> Added monthly revenue chart

backend/ASTU-backend-group-2/.gitignore
Description:
This pull request sets up environment variables for the blog project and includes the following updates:
Added a .gitignore file to prevent sensitive files (like .env) from being tracked in version control.
Created an env.example file as a template for required environment variables, ensuring that future contributors know which variables need to be set.
These changes enhance the security and maintainability of the project by keeping sensitive information out of the repository and providing clear guidelines for environment configuration.
=> feat: :sparkles: setup evironment variables

backend/ASTU-backend-group-4/blog/blog.go
- defining the entities, repository, and usecases
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/273
> Do you have any relevant URLs or Wiki pages that could help give background information for the …
=> 273 standardize blog domain

backend/ASTU-backend-group-4/chat/chat.go
- defining the chat domain
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/325
> Do you have any relevant URLs or Wiki pages that could help give background information for the changes in this …
=> feat: Add the chat domain definition

backend/ASTU-backend-group-4/blog/blog.go, backend/ASTU-backend-group-4/pkg/infrastructure/pagination.go
- define the pagination in the infrastructure 
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/414
> Do you have any relevant URLs or Wiki pages that could help give background information for the changes …
=> 414 create the infrastructure for pagination

backend/AASTU-backend-group-9/domain/token.go, backend/AASTU-backend-group-9/repository/token_repository.go
=> :fire: Authentication updated

backend/AAiT-backend-group-13/doc.md, backend/AAiT-backend-group-13/tasks.txt
Description:
This pull request introduces the following changes:
Entities:
Defined and structured entities relevant to the project requirements.
Endpoints: List of end points the project has. Request and response data of each end point.
Changes Made:
Created two files.  
Testing: Doesn't apply.
Notes:
These are the files we worked on together Aug 16 afternoon.
Checklist:
Reviewers:
Beka Birhnu
Ephrem Mamo
Thank you!
=> endpoints and entities doc

web/ASTU-web-group-2/banking-dashboard/app/components/lastTransaction/LastTransaction.tsx, web/ASTU-web-group-2/banking-dashboard/lib/service/TransactionService.tsx, web/ASTU-web-group-2/banking-dashboard/lib/store.ts
Added some middleware and reducers for the data fetching services in the **lib/store.tsx** file
=> fixed erros for data fetching and added middleware

web/AASTU-web-group-2/a2sv-banking-system/app/components/SecuritySetting.tsx
I modified the setting component.
=> Modified Setting Component

backend/AAiT-backend-group-13/.air.toml, backend/AAiT-backend-group-13/Dockerfile, backend/AAiT-backend-group-13/cmd/main.go, backend/AAiT-backend-group-13/docker-compose.yml, backend/AAiT-backend-group-13/go.mod
This PR introduces the foundational setup for the project, including:
- **Initial Directory Structure:** Organized the project files and directories according to best practices of clean architecture.
- **Docker Service:** Defined the `Dockerfile` and `docker-compose.yml` to streamline development, testing, and deployment in a consistent environment.
- **`air.toml` Configuration:** Added `air.toml` for live reloading during development, enhancing productivity by automatically rebuilding the application on code changes.
This setup ensures the project is ready for efficient development and containerized deployment from the outset.
=> build: Set up initial directory structure, define Docker service, and add air.toml

backend/AASTU-backend-group-6/Delivery/controllers/refresh_token_controller.go, backend/AASTU-backend-group-6/Delivery/routers/blog_router.go, backend/AASTU-backend-group-6/Delivery/routers/refresh_route.go, backend/AASTU-backend-group-6/Delivery/routers/route.go, backend/AASTU-backend-group-6/Delivery/routers/signup_route.go, backend/AASTU-backend-group-6/Domain/jwt_custom.go, backend/AASTU-backend-group-6/Domain/user_domain.go, backend/AASTU-backend-group-6/Infrastructure/lodeEnv.go, backend/AASTU-backend-group-6/Infrastructure/token_util.go, backend/AASTU-backend-group-6/Repositories/signup_repository.go, backend/AASTU-backend-group-6/Repositories/user_repository.go, backend/AASTU-backend-group-6/Usecases/signup_usecase.go, backend/AASTU-backend-group-6/air.cfg, backend/AASTU-backend-group-6/go.mod, backend/AASTU-backend-group-6/run.sh, backend/AASTU-backend-group-6/tmp/build-errors.log
[i finished the refresh end point see my work man approve the merge
=> Aastu.backend.g6.adane

backend/AAiT-backend-group-8/Delivery/main.go, backend/AAiT-backend-group-8/go.mod
This pull request introduces an organized folder structure for the project to improve maintainability, scalability, and ease of collaboration. The new folder structure is designed to follow best practices for organizing Go projects, ensuring that code is modular and logically separated based on functionality. This will make it easier for team members to navigate the project, work on specific features, and manage dependencies effectively.
=> add-folder-structure

web/AASTU-web-group-2/a2sv-banking-system/app/investments/page.tsx, web/AASTU-web-group-2/a2sv-banking-system/app/loans/page.tsx
=> page.tsx file updated

backend/AAiT-backend-group-8/Domain/domain.go, backend/AAiT-backend-group-8/Infrastructure/interfaces.go
This PR is for interfaces definition
=> feat: Interfaces Defined

backend/AAiT-backend-group-5/.gitignore, backend/AAiT-backend-group-5/Domain/Models/blogPost_model.go
structured the folders and initialized the project.
=> Aait.backend.g5.bisrat.initialize project structure

backend/AAiT-backend-group-11/domain/entities/token.go, backend/AAiT-backend-group-11/domain/interfaces/auth.go, backend/AAiT-backend-group-11/domain/interfaces/token.go, backend/AAiT-backend-group-11/domain/interfaces/user.go, backend/AAiT-backend-group-11/go.mod, backend/AAiT-backend-group-11/go.sum, backend/AAiT-backend-group-11/repository/user_repository.go, backend/AAiT-backend-group-11/service/auth_serivce.go, backend/AAiT-backend-group-11/service/token_service.go, backend/AAiT-backend-group-11/service/user_service.go
**Changes:**
1. **Removed demote and promote functions from UserRepository:**
- The `demoteUser` and `promoteUser` functions have been removed from the `UserRepository` as they were redundant and simply called the `updateUser` function in the `UserRepository`.
2. **Implemented Promote and Demote Services:**
- Added new `PromoteService` and `DemoteService` that encapsulate the logic for promoting and demoting users, respectively. These services handle the necessary updates to the user's role and permissions.
3. **Implemented Update and FindById Repo Functions:**
- Added new functions `updateUser` and `findUserById` to the `UserRepository` to handle updating user information and retrieving a user by their unique identifier.
4. **Implemented Invalidate Access/Refresh Token Services:**
- …
=> logout, promote/demote, others implemented

web/ASTU-web-group-2/banking-dashboard/app/AuthProvider.tsx, web/ASTU-web-group-2/banking-dashboard/app/api/auth/[...nextauth]/options.ts, web/ASTU-web-group-2/banking-dashboard/app/api/auth/[...nextauth]/signInUser.ts, web/ASTU-web-group-2/banking-dashboard/app/components/lastTransaction/LastTransaction.tsx, web/ASTU-web-group-2/banking-dashboard/app/components/lastTransaction/lastTransactionItems.tsx, web/ASTU-web-group-2/banking-dashboard/app/layout.tsx, web/ASTU-web-group-2/banking-dashboard/lib/service/TransactionService.ts, web/ASTU-web-group-2/banking-dashboard/package-lock.json, web/ASTU-web-group-2/banking-dashboard/package.json, web/ASTU-web-group-2/banking-dashboard/tsconfig.json, web/ASTU-web-group-2/banking-dashboard/types/next-auth.d.ts
- Wrapped root layout in session provider
- Added default data for last transaction if fetching data fails
- added next-auth.d.ts to get the session data while avoiding typescript error
=> Fixing session and data fetching errors

web/ASTU-web-group-1/astu.web.g1.bank-dash/package-lock.json, web/ASTU-web-group-1/astu.web.g1.bank-dash/src/lib/redux/slices/activeLoanSlice.ts, web/ASTU-web-group-1/astu.web.g1.bank-dash/src/lib/redux/slices/transactionSlice.ts, web/ASTU-web-group-1/astu.web.g1.bank-dash/src/store/store.ts
=> Add activeLoan Slice

backend/AAiT-backend-group-13/domain/errors/blog.go, backend/AAiT-backend-group-13/domain/errors/user.go, backend/AAiT-backend-group-13/domain/hash_interface/service.go, backend/AAiT-backend-group-13/domain/i_hash/service.go, backend/AAiT-backend-group-13/domain/models/blog/blog.go, backend/AAiT-backend-group-13/domain/models/user/user.go
added blog model and errors inside domain layer
=> Aait.backend.g13.ephrem.domain

backend/ASTU-backend-group-2/.gitignore, backend/ASTU-backend-group-2/domain/blog.go, backend/ASTU-backend-group-2/domain/login.go, backend/ASTU-backend-group-2/domain/profile.go, backend/ASTU-backend-group-2/domain/signup.go, backend/ASTU-backend-group-2/domain/user.go, backend/ASTU-backend-group-2/domain/validators/input_validator.go, backend/ASTU-backend-group-2/domain/validators/input_validator_test.go
User and Blog entities. This task involves defining the structure of these entities, including their attributes and relationships. Additionally, implemented necessary validations.
- also models for taking requests and and giving responses
- models for user login,profile,update
=> feat(astu-backend-g2) created models and entities 

backend/AAiT-backend-group-9/Blog_Starter/domain/blog.go, backend/AAiT-backend-group-9/Blog_Starter/domain/blog_rating.go, backend/AAiT-backend-group-9/Blog_Starter/domain/comment.go, backend/AAiT-backend-group-9/Blog_Starter/domain/like.go, backend/AAiT-backend-group-9/Blog_Starter/domain/login.go, backend/AAiT-backend-group-9/Blog_Starter/domain/logout.go, backend/AAiT-backend-group-9/Blog_Starter/domain/otp.go, backend/AAiT-backend-group-9/Blog_Starter/domain/signup.go, backend/AAiT-backend-group-9/Blog_Starter/domain/user.go, backend/AAiT-backend-group-9/Blog_Starter/go.mod, backend/AAiT-backend-group-9/Blog_Starter/go.sum, backend/AAiT-backend-group-9/Blog_Starter/utils/infrastructure/token_manager.go, backend/AAiT-backend-group-9/Blog_Starter/utils/tokenutil.go
​
Setting up the domain and interface setup
​
​
​
​
Impacts the domain and utils directory
​
​
​
=> setup the domains and interfaces

backend/AASTU-backend-group-9/domain/blog_interface.go, backend/AASTU-backend-group-9/domain/blog_model.go
Aastu.bakckend.g9.eyoel.new blog models and interfaces
=> blog_models_interface

backend/AASTU-backend-group-9/delivery/controller/blog_controller.go, backend/AASTU-backend-group-9/delivery/controller/login_controller.go, backend/AASTU-backend-group-9/delivery/middleware/auth_midd.go, backend/AASTU-backend-group-9/delivery/route/bolg_cruds_routes.go, backend/AASTU-backend-group-9/delivery/route/login_routes.go, backend/AASTU-backend-group-9/delivery/route/route.go, backend/AASTU-backend-group-9/domain/blog_interface.go, backend/AASTU-backend-group-9/domain/interface.go, backend/AASTU-backend-group-9/domain/jwt_custom.go, backend/AASTU-backend-group-9/domain/login.go, backend/AASTU-backend-group-9/domain/signup.go, backend/AASTU-backend-group-9/internal/tokenutil/auth_service.go, backend/AASTU-backend-group-9/internal/tokenutil/tokenutils.go, backend/AASTU-backend-group-9/repository/blog_repository.go, backend/AASTU-backend-group-9/usecase/blog_usecase.go, backend/AASTU-backend-group-9/usecase/login_usecase.go
the cruds opreation on blogs is DONE!
=> Blog_CRUDs_Finished

backend/ASTU-backend-group-5/cmd/app/main.go, backend/ASTU-backend-group-5/internal/domain/token.go, backend/ASTU-backend-group-5/internal/http/handlers/auth_handler.go, backend/ASTU-backend-group-5/internal/http/middleware/auth_middleware.go, backend/ASTU-backend-group-5/internal/http/routes/admin_routes.go, backend/ASTU-backend-group-5/internal/http/routes/auth_routes.go, backend/ASTU-backend-group-5/internal/http/routes/instantiate.go, backend/ASTU-backend-group-5/internal/http/routes/setup_routes.go, backend/ASTU-backend-group-5/internal/http/routes/user_routes.go, backend/ASTU-backend-group-5/internal/repository/mongodb/token_repo.go, backend/ASTU-backend-group-5/internal/repository/token_repo.go, backend/ASTU-backend-group-5/internal/usecase/token.go, backend/ASTU-backend-group-5/pkg/jwt/jwt.go, backend/ASTU-backend-group-5/pkg/mongo/client.go, backend/ASTU-backend-group-5/pkg/mongo/index.go
=> Astu.backend.g5.abdu.token blacklisting

backend/AASTU-backend-group-4/delivery/controller/user_controller/update_controller.go, backend/AASTU-backend-group-4/domain/user/user.go, backend/AASTU-backend-group-4/mongo/mongo.go, backend/AASTU-backend-group-4/repository/user_repository/updateUser_repository.go, backend/AASTU-backend-group-4/usecase/user_usecase/updateUser_usecase.go
profile management : User profile update
=> Created user profile update

backend/AASTU-backend-group-9/delivery/controller/blog_controller.go, backend/AASTU-backend-group-9/delivery/controller/login_controller.go, backend/AASTU-backend-group-9/delivery/route/bolg_cruds_routes.go, backend/AASTU-backend-group-9/domain/blog_interface.go, backend/AASTU-backend-group-9/domain/blog_model.go, backend/AASTU-backend-group-9/repository/blog_repository.go, backend/AASTU-backend-group-9/usecase/blog_usecase.go
=> :rocket: Popularity tracking

backend/ASTU-backend-group-4/auth/auth.go, backend/ASTU-backend-group-4/auth/mongodb/auth_storage.go
- This pull request focuses on improving the existing interfaces and their implementation within the codebase. The updates include refining the method signatures, optimizing the logic for better performance, and ensuring that the interfaces are more robust and easier to work with. These enhancements aim to increase code maintainability and scalability, providing a stronger foundation for future development.
- These changes should improve the overall functionality and efficiency of the system without affecting existing workflows.
> What Jira items …
=> 576 Enhance interface and their implementation

backend/ASTU-backend-group-2/domain/blog.go, backend/ASTU-backend-group-2/domain/login.go, backend/ASTU-backend-group-2/domain/profile.go, backend/ASTU-backend-group-2/domain/signup.go, backend/ASTU-backend-group-2/domain/user.go
```markdown
This pull request introduces new interfaces and refactors existing ones across multiple layers, including Blog, User Profile, Login, and Signup. 
These changes aim to standardize method signatures, improve separation of concerns, and enhance the overall architecture of the application.
Created the `BlogRepository` interface to manage data access operations related to blogs and comments:
- `GetAllBlogs(c context.Context) ([]Blog, error)`: Retrieves all blogs.
- `GetBlogByID(c context.Context, blogID string) (Blog, error)`: Retrieves a single blog by ID.
- `CreateBlog(c context.Context, newBlog *Blog) error`: Creates a new blog.
- `UpdateBlog(c context.Context, blogID string, updatedBlog *Blog) error`: Updates an existing blog by ID.
- `DeleteBlog(c context.Context, blogID …
```
=> feat: :sparkles: create intrfaces for each layer

backend/AAiT-backend-group-9/Blog_Starter/api/controller/blog_controller.go, backend/AAiT-backend-group-9/Blog_Starter/api/middleware/auth_middleware.go, backend/AAiT-backend-group-9/Blog_Starter/api/router/router.go, backend/AAiT-backend-group-9/Blog_Starter/main.go, backend/AAiT-backend-group-9/Blog_Starter/repository/blog_repository.go, backend/AAiT-backend-group-9/Blog_Starter/usecase/blog_usecase.go
This is a commit from eyob
The necessary Blog CRUD features are implemented following clean architecture
Blog Repository, usecase, and controller are implemented
=> add blog crud features

web/AASTU-web-group-4/next-bank/components/AccountBarChart.tsx, web/AASTU-web-group-4/next-bank/components/InvoicesCard.tsx
=> account page

backend/AASTU-backend-group-7/Delivery/controllers/blog_controller.go, backend/AASTU-backend-group-7/Delivery/controllers/comment_controller.go, backend/AASTU-backend-group-7/Delivery/controllers/tag_controller.go, backend/AASTU-backend-group-7/Delivery/routers/blog_router.go, backend/AASTU-backend-group-7/Domain/blog.go, backend/AASTU-backend-group-7/Domain/interfaces.go, backend/AASTU-backend-group-7/Domain/user.go, backend/AASTU-backend-group-7/Dtos/user_dto.go, backend/AASTU-backend-group-7/Repositories/auth_repository.go, backend/AASTU-backend-group-7/Repositories/blog_repo.go, backend/AASTU-backend-group-7/Repositories/comments_repository.go, backend/AASTU-backend-group-7/Repositories/tags_repostitory.go, backend/AASTU-backend-group-7/UseCases/blog_usecase.go, backend/AASTU-backend-group-7/UseCases/comments_usecase.go, backend/AASTU-backend-group-7/UseCases/tag_usecase.go, backend/AASTU-backend-group-7/tmp/build-errors.log
- Added more routes, delete comments
- remodeled models
=> Aastu.backend.g7.bini.posts

backend/AASTU-backend-group-9/delivery/controller/login_controller.go, backend/AASTU-backend-group-9/delivery/controller/profile_controller.go, backend/AASTU-backend-group-9/delivery/route/login_routes.go, backend/AASTU-backend-group-9/delivery/route/logout_routes.go, backend/AASTU-backend-group-9/delivery/route/profile_route.go, backend/AASTU-backend-group-9/delivery/route/route.go, backend/AASTU-backend-group-9/domain/interface.go, backend/AASTU-backend-group-9/internal/tokenutil/tokenutils.go, backend/AASTU-backend-group-9/usecase/blog_usecase.go, backend/AASTU-backend-group-9/usecase/login_usecase.go
=> refresh_token_finished

backend/AAiT-backend-group-13/delivery/base/base.go, backend/AAiT-backend-group-13/delivery/user/user_controller.go, backend/AAiT-backend-group-13/usecases_sof/user/command/command.go, backend/AAiT-backend-group-13/usecases_sof/user/command/handler.go, backend/AAiT-backend-group-13/usecases_sof/user/command/login_handler.go, backend/AAiT-backend-group-13/usecases_sof/user/command/signup_handler.go, backend/AAiT-backend-group-13/usecases_sof/user/result/result.go, backend/AAiT-backend-group-13/usecases_sof/utils/command/command.go, backend/AAiT-backend-group-13/usecases_sof/utils/i_email/email_service.go, backend/AAiT-backend-group-13/usecases_sof/utils/i_email/mail.go, backend/AAiT-backend-group-13/usecases_sof/utils/i_jwt/jwt_service.go, backend/AAiT-backend-group-13/usecases_sof/utils/i_repo/user_repo.go, backend/AAiT-backend-group-13/usecases_sof/utils/query/query.go
Added BaseController: Centralized common response methods.
Updated Controllers: Controllers now extend BaseController to leverage shared methods.
Errors due to use case and controller incompatability -- will be fixed once use cases are done.
Commands:
signUpCommand and LoginCommand structs for user sign-up and login data.
Handler:
HandleSignup and HandleLogin methods handle user creation, validation, and JWT token generation.
Utility Interfaces:
Introduced interfaces for user repository, JWT services, password hashing, and email sending.
Email Service:
Added Mail struct and service interface for sending sign-up confirmation emails.
JWT Service:
Added interface for generating and decoding JWT tokens.
@beka-birhanu 
@Efamamo
=> Aait.backend.g13.sofonyas.usecase.user

backend/ASTU-backend-group-4/chat/chat.go, backend/ASTU-backend-group-4/chat/errors.go, backend/ASTU-backend-group-4/chat/mongodb/chat_storage.go
- repository implementation for the chat domain by creating a struct that implements the repository interface in the chat domain.
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/437
> Do you have any …
=> Implement a repository for the chat domain

node_modules/@babel/runtime/helpers/classApplyDescriptorDestructureSet.js, web/ASTU-web-group-2/banking-dashboard/app/components/transaction/Transaction.tsx, web/ASTU-web-group-2/banking-dashboard/app/components/transactionsDisplay/TransactionsDisplay.tsx, web/ASTU-web-group-2/banking-dashboard/app/components/transactionsTable/TransactionsTable.tsx, web/ASTU-web-group-2/banking-dashboard/package-lock.json, web/ASTU-web-group-2/banking-dashboard/package.json
https://github.com/user-attachments/assets/29474c4b-9268-4a6f-a606-01c8f31aa3aa
=> Implement integration with api

backend/AAiT-backend-group-7/blog_project/domain/blog.go
[add search by author, tags, and title](https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/pull/838)
=> add searching by title, tags and author

backend/AASTU-backend-group-5/delivery/controller/user.controller.go, backend/AASTU-backend-group-5/domain/user.model.go, backend/AASTU-backend-group-5/domain/user_interface.go, backend/AASTU-backend-group-5/mocks/User_Controller_interface.go, backend/AASTU-backend-group-5/mocks/User_Repository_interface.go, backend/AASTU-backend-group-5/mocks/User_Usecase_interface.go, backend/AASTU-backend-group-5/repository/user.repository.go, backend/AASTU-backend-group-5/usecase/user.usecase.go
=> Aastu.backend.g5.upass

backend/ASTU-backend-group-4/blog/usecase.go
- starting the blog use case implementation
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/844
> Do you have any relevant URLs or Wiki pages that could help give background information for the changes in …
=> feat: add blog use case implemenation boilerplate code

backend/ASTU-backend-group-4/blog/blog.go, backend/ASTU-backend-group-4/blog/usecase.go
- add implementation for the create blog method.
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/853
> Do you have any relevant URLs or Wiki pages that could help give background information for the …
=> 853 implement the createblog use case for the blog domain

backend/AASTU-backend-group-9/config/env.go, backend/AASTU-backend-group-9/delivery/controller/ai_controller.go, backend/AASTU-backend-group-9/delivery/route/ai_routes.go, backend/AASTU-backend-group-9/delivery/route/route.go, backend/AASTU-backend-group-9/domain/ai_interface.go, backend/AASTU-backend-group-9/usecase/ai_usecase.go
=> :zap: AI Integrated

backend/AAiT-backend-group-8/Delivery/Controller/comment_controller.go, backend/AAiT-backend-group-8/Delivery/Controller/controller.go, backend/AAiT-backend-group-8/Delivery/Controller/user_controller.go, backend/AAiT-backend-group-8/Delivery/Routes/routes.go, backend/AAiT-backend-group-8/Delivery/main.go, backend/AAiT-backend-group-8/Infrastructure/Infrastructure.go, backend/AAiT-backend-group-8/Repository/comment_repository.go, backend/AAiT-backend-group-8/Repository/like_repository.go, backend/AAiT-backend-group-8/Usecase/comment_usecase.go, backend/AAiT-backend-group-8/Usecase/like_usecase.go, backend/AAiT-backend-group-8/Usecase/user_usecase.go
Compared and combined the different version
=> created like and comment features

backend/AASTU-backend-group-6/Delivery/controllers/ai_controller.go, backend/AASTU-backend-group-6/Delivery/controllers/handleresponse.go, backend/AASTU-backend-group-6/Delivery/controllers/oauth_controller.go, backend/AASTU-backend-group-6/Delivery/controllers/signup_controller.go, backend/AASTU-backend-group-6/Delivery/routers/ai_route.go, backend/AASTU-backend-group-6/Delivery/routers/route.go, backend/AASTU-backend-group-6/Domain/ai_domain.go, backend/AASTU-backend-group-6/Domain/prompt.go, backend/AASTU-backend-group-6/Infrastructure/aiResponse.go, backend/AASTU-backend-group-6/Infrastructure/lodeEnv.go, backend/AASTU-backend-group-6/Usecases/ai_usecase.go, backend/AASTU-backend-group-6/Usecases/signup_usecase.go, backend/AASTU-backend-group-6/go.mod
keyword based blog idea generator integration done
=> ai integration Done 

web/AASTU-web-group-2/a2sv-banking-system/app/accounts/page.tsx, web/AASTU-web-group-2/a2sv-banking-system/app/api/auth/[...nextauth]/options.ts, web/AASTU-web-group-2/a2sv-banking-system/app/components/Navigation.tsx, web/AASTU-web-group-2/a2sv-banking-system/app/components/Sidebar.tsx, web/AASTU-web-group-2/a2sv-banking-system/app/page.tsx, web/AASTU-web-group-2/a2sv-banking-system/lib/api/cardController.ts
=> fixed some usernames

web/AASTU-web-group-2/a2sv-banking-system/app/components/Sidebar.tsx
=> Fixed some navigation issues

backend/AAiT-backend-group-13/usecases_sof/user/command/login_handler.go, backend/AAiT-backend-group-13/usecases_sof/user/command/signup_handler.go
Resolved conflicts in usercase
@beka-birhanu 
@Efamamo
=> Confilicts resolved

backend/AAiT-backend-group-8/Delivery/Controller/comment_controller.go, backend/AAiT-backend-group-8/Delivery/Controller/controller.go, backend/AAiT-backend-group-8/Delivery/Controller/user_controller.go, backend/AAiT-backend-group-8/Delivery/Routes/routes.go, backend/AAiT-backend-group-8/Delivery/main.go, backend/AAiT-backend-group-8/Domain/user_domain.go, backend/AAiT-backend-group-8/Repository/token_repository.go, backend/AAiT-backend-group-8/Repository/user_repository.go, backend/AAiT-backend-group-8/Usecase/user_usecase.go
this pull request for login functionlity and bug fix
=> fix some error on routes and login

backend/AAiT-backend-group-3/internal/delivery/controllers/user_controller.go, backend/AAiT-backend-group-3/internal/delivery/routers/blog_routers.go, backend/AAiT-backend-group-3/internal/delivery/routers/router.go, backend/AAiT-backend-group-3/internal/delivery/routers/user_routers.go, backend/AAiT-backend-group-3/internal/domain/dtos/reset_password.go, backend/AAiT-backend-group-3/internal/infrastructures/services/email_service.go, backend/AAiT-backend-group-3/internal/infrastructures/services/jwt_service.go, backend/AAiT-backend-group-3/internal/infrastructures/services/otp_service.go, backend/AAiT-backend-group-3/internal/infrastructures/services/validation_service.go, backend/AAiT-backend-group-3/internal/repositories/implementation/user_repository.go, backend/AAiT-backend-group-3/internal/repositories/interfaces/user_repository_interface.go, backend/AAiT-backend-group-3/internal/usecases/user_usecase.go
added email service, OTP service, validation service and added auth routes.
=> AAiT backend g3 infrastructure layer services

web/AASTU-web-group-2/a2sv-banking-system/app/accounts/page.tsx
=> Final Push for this branch

web/AASTU-web-group-6/bankdash/app/components/Accounts/LastTransList.tsx
add helper function to LastTransList
=> add helper function to LastTransList

backend/ASTU-backend-group-4/auth/auth.go, backend/ASTU-backend-group-4/auth/mongodb/auth_storage.go
This pull request introduces the GetUserById feature to the project. 
the feature includes the following updates:
- Implemented the GetUserById method in the appropriate service/repository layer.
- Added necessary validation and error handling to ensure robust functionality.
- Included unit tests to verify the correctness of the GetUserById implementation.
This feature will allow the application to retrieve user details by their unique identifier, enhancing the user management capabilities of the system.
> What Jira items (Epics, Stories, Tasks, or …
=> Add get user by ID functionality

backend/AAiT-backend-group-13/infrastructure/jwt/jwt_service.go
This PR updates the JWT package within the infrastructure layer to enhance security, performance, and maintainability. The change involves replacing the previous JWT implementation with a more robust or updated package that aligns with current standards.
What has changed:
Replaced the existing JWT package with the new implementation in the infrastructure layer.
Updated all relevant functions and methods to utilize the new package.
Modified unit tests and integration tests to ensure compatibility with the updated JWT package.
Refactored code to improve readability and maintainability in relation to JWT handling.
Why this change was made:
To leverage the improved features and security of the new JWT package.
To ensure that the project remains up-to-date with modern authentication practices. …
=> jwt at infrastructure

backend/ASTU-backend-group-4/blog/blog.go, backend/ASTU-backend-group-4/blog/usecase.go
- add implementation for the delete blog
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/972
> Do you have any relevant URLs or Wiki pages that could help give background information for the changes in …
=> 972 add implementation for delete blog

backend/ASTU-backend-group-2/repository/blog_repository.go
PR Description: Implement Blog Repository Functions for Sorting, CRUD Operations, and Retrieval
This PR introduces several key functions to the `blogRepository` struct to handle various operations related to blogs in the database. The new functions include sorting blogs by different criteria (date, comments, likes), as well as essential CRUD operations (Create, Read, Update, Delete) and retrieving all blogs or a specific blog by its ID.
- `SortByDate`: Retrieves blogs sorted by their creation date in ascending order.
- `SortByComment`: Retrieves blogs sorted by the number of comments in ascending order.
- `SortByLikes`: Retrieves blogs sorted by the number of likes in ascending order.
```go
func (br *blogRepository) SortByDate(c context.Context) ([]domain.Blog, error) { ... }
func (br …
```
=> feat: Refactor blog repository methods

backend/AAiT-backend-group-13/infrastructure/jwt/jwt_service.go, backend/AAiT-backend-group-13/usecase/user/query/email_validation_handler.go
The bugs we saw at infrastructure and use cases are fixed.
REviewers:
@beka-birhanu 
@Efamamo
=> bugs fixed

backend/AAiT-backend-group-10/delivery/controllers/blog.go, backend/AAiT-backend-group-10/delivery/controllers/user.go, backend/AAiT-backend-group-10/delivery/router/router.go, backend/AAiT-backend-group-10/usecases/blog.go
Authorized delete and update blog
=> Aait.backend.g10.abenezer.blog auth

backend/AASTU-backend-group-7/Config/env.go, backend/AASTU-backend-group-7/Delivery/controllers/auth_controller.go, backend/AASTU-backend-group-7/Delivery/controllers/chat_controller.go, backend/AASTU-backend-group-7/Delivery/main.go, backend/AASTU-backend-group-7/Delivery/routers/auth_router.go, backend/AASTU-backend-group-7/Domain/account.go, backend/AASTU-backend-group-7/Domain/interfaces.go, backend/AASTU-backend-group-7/Domain/user.go, backend/AASTU-backend-group-7/Dtos/user_dto.go, backend/AASTU-backend-group-7/Repositories/auth_repository.go, backend/AASTU-backend-group-7/UseCases/auth_usecase.go, backend/AASTU-backend-group-7/go.mod, backend/AASTU-backend-group-7/go.sum
- email verification
- oauth updates
- refactor for testing
- email validator on register
=> Aastu.backend.g7.abel.oauth

web/AASTU-web-group-2/a2sv-banking-system/lib/api/companyControl.ts, web/AASTU-web-group-2/a2sv-banking-system/lib/api/userControl.ts
=> Modified control files

web/ASTU-web-group-2/banking-dashboard/app/components/charts/BalanceHistoryChart.tsx, web/ASTU-web-group-2/banking-dashboard/app/components/charts/WeeklyActivityChart.tsx
update the charts because of the api response is changed
=> Astu.web.g2.wondmeneh940 chart api integration

backend/AAiT-backend-group-10/delivery/controllers/comment.go, backend/AAiT-backend-group-10/delivery/controllers/like.go, backend/AAiT-backend-group-10/delivery/router/router.go, backend/AAiT-backend-group-10/go.mod, backend/AAiT-backend-group-10/go.sum, backend/AAiT-backend-group-10/repositories/comment.go, backend/AAiT-backend-group-10/repositories/like.go, backend/AAiT-backend-group-10/usecases/comment.go, backend/AAiT-backend-group-10/usecases/interfaces/comment_repo_interface.go, backend/AAiT-backend-group-10/usecases/interfaces/like_repo_interface.go, backend/AAiT-backend-group-10/usecases/like.go
Integrated the middleware to routers
=> Aait.backend.g10.samrawit.integration of middlware to router

web/AASTU-web-group-2/a2sv-banking-system/app/accounts/page.tsx, web/AASTU-web-group-2/a2sv-banking-system/app/api/auth/[...nextauth]/options.ts, web/AASTU-web-group-2/a2sv-banking-system/app/api/auth/signin/components/Forms.tsx, web/AASTU-web-group-2/a2sv-banking-system/lib/api/authenticationController.ts, web/AASTU-web-group-2/a2sv-banking-system/lib/api/cardController.ts, web/AASTU-web-group-2/a2sv-banking-system/package-lock.json, web/AASTU-web-group-2/a2sv-banking-system/package.json, web/AASTU-web-group-2/a2sv-banking-system/types/cardController.Interface.ts
fixed some build issues along with changes to the way we are going to access the access token,
I have also implemented a logic for refresh token inside the options
=> Aastu.web.g2.rebuma.api integration

backend/ASTU-backend-group-4/blog/blog.go, backend/ASTU-backend-group-4/blog/usecase.go
- add implementation for the delete comment
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/995
> Do you have any relevant URLs or Wiki pages that could help give background information for the changes in …
=> 995 add implementation for delete comment

backend/ASTU-backend-group-4/chat/chat.go, backend/ASTU-backend-group-4/chat/forms.go, backend/ASTU-backend-group-4/chat/usecase.go
- created the CreatChat method for the usecase struct
- added input validation using infrstructure.validator
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/842
> Do you have any relevant URLs or Wiki …
=> implement createchat usecase for the chat domain

backend/AAiT-backend-group-10/domain/customError.go
=> Aait.backend.g10.custom error

backend/AASTU-backend-group-9/delivery/controller/blog_controller.go, backend/AASTU-backend-group-9/delivery/route/bolg_cruds_routes.go, backend/AASTU-backend-group-9/domain/blog_interface.go, backend/AASTU-backend-group-9/domain/blog_model.go, backend/AASTU-backend-group-9/domain/comment_interface.go, backend/AASTU-backend-group-9/repository/blog_repository.go, backend/AASTU-backend-group-9/repository/comment_repository.go, backend/AASTU-backend-group-9/repository/popularity_repository.go, backend/AASTU-backend-group-9/usecase/blog_usecase.go
=> comment_like_dislike_DONE

backend/AAiT-backend-group-1/delivery/controllers/userController.go, backend/AAiT-backend-group-1/infrastructure/jwt_service.go, backend/AAiT-backend-group-1/infrastructure/mail/mail_service.go, backend/AAiT-backend-group-1/infrastructure/mail/templates/password_reset.html, backend/AAiT-backend-group-1/infrastructure/mail/templates/verification.html, backend/AAiT-backend-group-1/infrastructure/middleware_service.go, backend/AAiT-backend-group-1/infrastructure/password_service.go, backend/AAiT-backend-group-1/repository/session_repository.go, backend/AAiT-backend-group-1/repository/user_repository.go, backend/AAiT-backend-group-1/usecases/user_usecase.go
=> rebase successfull, added the user side

web/AASTU-web-group-2/a2sv-banking-system/types/transactionController.interface.ts
Transaction controller updated by new API responses.
=> Aastu.web.g2.mike.quick transfer

web/AASTU-web-group-4/next-bank/app/(root)/loans/page.tsx, web/AASTU-web-group-4/next-bank/constants/index.ts, web/AASTU-web-group-4/next-bank/middleware.ts, web/AASTU-web-group-4/next-bank/services/activeloan.tsx
Fetch the api for the loan page
=> Fetch the api for the loan page

web/ASTU-web-group-1/astu.web.g1.bank-dash/src/app/bank-dash/transactions/page.tsx, web/ASTU-web-group-1/astu.web.g1.bank-dash/src/components/RecentTransactionTable/RecentTransactionDescription.tsx, web/ASTU-web-group-1/astu.web.g1.bank-dash/src/components/RecentTransactionTable/RecentTransactionTable.tsx
This PR introduces several key improvements to the RecentTransactionTable component:
Pagination: Added pagination functionality to handle large datasets. The table now displays a limited number of transactions per page with "Previous" and "Next" buttons for easy navigation.
Dynamic Content Handling: Updated the component to fetch and display transaction data dynamically, ensuring the correct page data is rendered based on the current pagination state.
UI Enhancements:
The RecentTransactionDescription component is incorporated to display transaction descriptions with proper truncation and overflow handling.
Improved the layout and responsiveness of the table and pagination controls, making it more user-friendly across various screen sizes.
=> Astu.web.g1.mubarak.926 astu web g1 mubarek recent transaction data population

backend/AAiT-backend-group-10/delivery/controllers/auth.go, backend/AAiT-backend-group-10/delivery/controllers/blog.go, backend/AAiT-backend-group-10/delivery/controllers/comment.go, backend/AAiT-backend-group-10/delivery/controllers/like.go, backend/AAiT-backend-group-10/delivery/controllers/user.go, backend/AAiT-backend-group-10/domain/customError.go, backend/AAiT-backend-group-10/infrastructures/email.go, backend/AAiT-backend-group-10/infrastructures/hashing.go, backend/AAiT-backend-group-10/infrastructures/jwt.go, backend/AAiT-backend-group-10/infrastructures/jwt_samri.go, backend/AAiT-backend-group-10/repositories/blog.go, backend/AAiT-backend-group-10/repositories/comment.go, backend/AAiT-backend-group-10/repositories/like.go, backend/AAiT-backend-group-10/repositories/user.go, backend/AAiT-backend-group-10/usecases/auth.go, backend/AAiT-backend-group-10/usecases/blog.go, backend/AAiT-backend-group-10/usecases/comment.go, backend/AAiT-backend-group-10/usecases/interfaces/blog_repo_interface.go, backend/AAiT-backend-group-10/usecases/interfaces/comment_repo_interface.go, backend/AAiT-backend-group-10/usecases/interfaces/like_repo_interface.go, backend/AAiT-backend-group-10/usecases/interfaces/user_repo_interface.go, backend/AAiT-backend-group-10/usecases/like.go, backend/AAiT-backend-group-10/usecases/user.go
=> Added custom errors

backend/ASTU-backend-group-4/blog/usecase.go
- add implementation for get blogs
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/1072
> Do you have any relevant URLs or Wiki pages that could help give background information for the changes in this …
=> 1072 add implementation for get blogs

backend/ASTU-backend-group-4/blog/usecase.go
- created the CreatChat method for the usecase struct
- added input validation using infrstructure.validator
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/1075
> Do you have any relevant URLs or Wiki …
=> feat(blog): add implementation for get comments by blog id

backend/ASTU-backend-group-4/blog/blog.go, backend/ASTU-backend-group-4/blog/usecase.go
- add implementation for search blogs
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/1077
> Do you have any relevant URLs or Wiki pages that could help give background information for the changes in this …
=> 1077 add implementation for search blogs

backend/ASTU-backend-group-4/blog/blog.go, backend/ASTU-backend-group-4/blog/usecase.go
- add implementation for update blog
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/1079
> Do you have any relevant URLs or Wiki pages that could help give background information for the changes in this …
=> 1079 add implementation for update blog

backend/AAiT-backend-group-1/delivery/controllers/userController.go, backend/AAiT-backend-group-1/delivery/router/router.go, backend/AAiT-backend-group-1/domain/infrastructure_interfaces.go, backend/AAiT-backend-group-1/domain/session.go, backend/AAiT-backend-group-1/domain/usecase_interfaces.go, backend/AAiT-backend-group-1/go.mod, backend/AAiT-backend-group-1/go.sum, backend/AAiT-backend-group-1/infrastructure/cache_service.go, backend/AAiT-backend-group-1/infrastructure/jwt_service.go, backend/AAiT-backend-group-1/usecases/user_usecase.go
before modifying the middleware to handle logout, finished the user part
=> Aait.backend.g1.amha

backend/ASTU-backend-group-5/internal/http/handlers/user_handlers.go, backend/ASTU-backend-group-5/pkg/checker/email_checker.go, backend/ASTU-backend-group-5/pkg/checker/password_checker.go
Title: Improve Password Validation Logic and Email validation logic
Description: This pull request enhances the password validation logic in the [password_checker.go]. The following changes were made:
Added Password Length Check:
Ensured that the password length is at least 8 characters.
Enhanced Character Checks and correctness of email
=> email and password correctness is checking is added

web/AASTU-web-group-4/next-bank/app/(root)/accounts/page.tsx, web/AASTU-web-group-4/next-bank/components/CreditCard.tsx, web/AASTU-web-group-4/next-bank/components/InvoicesCard.tsx, web/AASTU-web-group-4/next-bank/components/LastTransactionCard.tsx
fixed the responsive design problem of the accounts page
=> fixed UI problems on the accounts page

backend/ASTU-backend-group-2/api/controller/login_controller.go, backend/ASTU-backend-group-2/api/controller/signup_controller.go, backend/ASTU-backend-group-2/domain/login.go, backend/ASTU-backend-group-2/domain/signup.go, backend/ASTU-backend-group-2/domain/user.go, backend/ASTU-backend-group-2/repository/user_repository.go, backend/ASTU-backend-group-2/usecase/login_usecase.go, backend/ASTU-backend-group-2/usecase/signup_usecase.go, backend/ASTU-backend-group-2/usecase/user_usecase.go
**Description:**
This PR introduces two new controllers: `SignupController` and `LoginController`, responsible for handling user signup and login functionalities. These controllers integrate with the respective use cases and environment configurations.
**Changes:**
1. **SignupController:**
- Implements the `Signup` method to handle user registration.
- Validates the request, checks if the user already exists, encrypts the password, determines user role, and creates a new user.
- Generates access and refresh tokens for the user upon successful registration.
2. **LoginController:**
- Implements the `Login` method to handle user authentication.
- Validates user credentials, generates new access and refresh tokens, and updates the user's refresh token in the database.
**Note:**
- Both …
=> Astu.backend.g2.saleamlak.create login and signup controllers

backend/AAiT-backend-group-13/delivery/controller/user/controller.go, backend/AAiT-backend-group-13/example.env, backend/AAiT-backend-group-13/infrastructure/hash/service.go, backend/AAiT-backend-group-13/infrastructure/repo/user/dto.go, backend/AAiT-backend-group-13/infrastructure/repo/user/user.go, backend/AAiT-backend-group-13/usecase/password_reset/code_send_handler.go, backend/AAiT-backend-group-13/usecase/user/command/login_handler.go, backend/AAiT-backend-group-13/usecase/user/command/signup_handler.go
Changes:
Signup Flow:
Fixed an issue where the signup process would fail silently due to incorrect error handling in the repository layer.
Improved validation checks for user inputs to prevent invalid data from being processed.
Enhanced security by hashing sensitive data before storage.
Login Flow:
Resolved a bug where users were unable to log in due to token generation errors.
Improved error messages for failed login attempts to provide more clarity to users.
Refactored the login logic to optimize performance and reduce response times.
Reset Code Functionality:
Fixed the reset code generation to ensure it is unique and expires after the intended duration.
Updated the reset code validation logic to handle edge cases where the code might be expired or tampered with.
Improved the user …
=> fixes for login singup  reset code

web/AASTU-web-group-4/next-bank/app/(root)/loans/page.tsx
worked on loans page ui problems
=> Aastu.web.g4.natnael.loans

web/AASTU-web-group-4/next-bank/app/(root)/services/page.tsx, web/AASTU-web-group-4/next-bank/components/BankservicesList.tsx, web/AASTU-web-group-4/next-bank/components/Loginform.tsx, web/AASTU-web-group-4/next-bank/components/Navbar.tsx, web/AASTU-web-group-4/next-bank/services/bankseervice.tsx
added a dropdown on the profile on the frontpage
=> new changes

backend/AASTU-backend-group-9/delivery/controller/user_controller.go, backend/AASTU-backend-group-9/domain/login.go
small_update on user controller
=> :bug:smallupdate

backend/AASTU-backend-group-8/delivery/controllers/profile_handler.go, backend/AASTU-backend-group-8/delivery/routers/router.go, backend/AASTU-backend-group-8/domain/profile.go, backend/AASTU-backend-group-8/usecases/profile_usecase.go
=> added avatars

backend/ASTU-backend-group-4/internal/http/gin/chat.go
- make the CreateChatHandler function to accept a user id from the gin.context which is passed as a parameter.
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/1290
> Do you have any relevant URLs or Wiki …
=> make the CreateChatHandler function to accept a user id from the context

backend/AASTU-backend-group-9/delivery/controller/blog_controller.go, backend/AASTU-backend-group-9/delivery/route/bolg_cruds_routes.go, backend/AASTU-backend-group-9/domain/blog_interface.go, backend/AASTU-backend-group-9/domain/blog_model.go, backend/AASTU-backend-group-9/repository/blog_repository.go, backend/AASTU-backend-group-9/usecase/blog_usecase.go
=> :bug:small_update_on_blog_cruds

backend/ASTU-backend-group-4/internal/http/gin/blog.go
- implement the create blog handler function
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/1278
> Do you have any relevant URLs or Wiki pages that could help give background information for the changes …
=> 1278 start the blog controllers

web/AASTU-web-group-2/a2sv-banking-system/app/loans/page.tsx
=> loans added

web/AASTU-web-group-2/a2sv-banking-system/app/investments/components/LineChart.tsx, web/AASTU-web-group-2/a2sv-banking-system/app/investments/components/Monthly.tsx, web/AASTU-web-group-2/a2sv-banking-system/app/investments/page.tsx
=> added investment

backend/AASTU-backend-group-9/delivery/controller/blog_controller.go, backend/AASTU-backend-group-9/domain/blog_interface.go, backend/AASTU-backend-group-9/repository/blog_repository.go, backend/AASTU-backend-group-9/usecase/blog_usecase.go, backend/AASTU-backend-group-9/usecase/signup_usecase.go, backend/AASTU-backend-group-9/usecase/user_usecase.go
=> :fire:filter_update

backend/ASTU-backend-group-4/internal/http/gin/chat.go
- implemented the function that handles an http request for retrieving a chat.
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/1273
> Do you have any relevant URLs or Wiki pages that could help give …
=> add getchat handler function implementation

backend/ASTU-backend-group-4/internal/http/gin/blog.go
- implemented the function that handles an http request for updating blog.
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/1384
> Do you have any relevant URLs or Wiki pages that could help give background …
=> 1384 add implementation for update blog controller

backend/ASTU-backend-group-4/internal/http/gin/blog.go
- implemented the function that handles an http request for deleting blog.
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/1386
> Do you have any relevant URLs or Wiki pages that could help give background …
=> feat(blog): add implementation for delete blog controller

backend/ASTU-backend-group-4/chat/chat.go, backend/ASTU-backend-group-4/chat/usecase.go, backend/ASTU-backend-group-4/internal/http/gin/chat.go
- implemented the function that handles an http request for getting all chats created by a user.
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/1371
> Do you have any relevant URLs or Wiki pages that …
=> add getchats handler function implementation

backend/AAiT-backend-group-8/Delivery/Controller/blog_controller.go, backend/AAiT-backend-group-8/Delivery/Controller/comment_controller.go, backend/AAiT-backend-group-8/Delivery/Controller/like_controller.go, backend/AAiT-backend-group-8/Delivery/Controller/user_controller.go, backend/AAiT-backend-group-8/Delivery/Routes/routes.go, backend/AAiT-backend-group-8/Delivery/main.go, backend/AAiT-backend-group-8/Domain/blog_domain.go, backend/AAiT-backend-group-8/Domain/user_domain.go, backend/AAiT-backend-group-8/Infrastructure/auth_middleware.go, backend/AAiT-backend-group-8/Infrastructure/jwt_service.go, backend/AAiT-backend-group-8/Infrastructure/mongodb/user.go, backend/AAiT-backend-group-8/Usecase/user_usecase.go
=> bug fix on yige's recent PR

web/ASTU-web-group-2/banking-dashboard/app/(mainDash)/accounts/page.tsx, web/ASTU-web-group-2/banking-dashboard/app/(mainDash)/credit-cards/page.tsx, web/ASTU-web-group-2/banking-dashboard/app/(mainDash)/page.tsx, web/ASTU-web-group-2/banking-dashboard/app/(mainDash)/transactions/page.tsx, web/ASTU-web-group-2/banking-dashboard/app/api/auth/[...nextauth]/options.ts, web/ASTU-web-group-2/banking-dashboard/app/api/auth/[...nextauth]/signInUser.ts, web/ASTU-web-group-2/banking-dashboard/app/components/addNewCard/AddNewCard.tsx, web/ASTU-web-group-2/banking-dashboard/app/components/card/CardForCreditCards.tsx, web/ASTU-web-group-2/banking-dashboard/app/components/cardDisplay/CardDisplay.tsx, web/ASTU-web-group-2/banking-dashboard/app/components/charts/DebitCreditOverviewChart.tsx, web/ASTU-web-group-2/banking-dashboard/app/components/charts/MyExpenseChart.tsx, web/ASTU-web-group-2/banking-dashboard/app/components/creditCard/CreditCard.tsx, web/ASTU-web-group-2/banking-dashboard/app/components/lastTransaction/LastTransaction.tsx, web/ASTU-web-group-2/banking-dashboard/app/components/transactionsDisplay/TransactionsDisplay.tsx, web/ASTU-web-group-2/banking-dashboard/app/components/transactionsTable/TransactionsTable.tsx, web/ASTU-web-group-2/banking-dashboard/lib/service/BankService.tsx, web/ASTU-web-group-2/banking-dashboard/lib/service/CardService.tsx, web/ASTU-web-group-2/banking-dashboard/lib/service/CompanyService.tsx, web/ASTU-web-group-2/banking-dashboard/lib/service/LoanService.tsx, web/ASTU-web-group-2/banking-dashboard/lib/service/TransactionService.ts, web/ASTU-web-group-2/banking-dashboard/lib/service/UserService.tsx, web/ASTU-web-group-2/banking-dashboard/lib/store.ts, web/ASTU-web-group-2/banking-dashboard/package-lock.json, web/ASTU-web-group-2/banking-dashboard/package.json
=> Astu.web.g2.wondmeneh.1147 make the dashboard responsive

backend/ASTU-backend-group-4/internal/http/gin/chat.go
- implemented the function that handles an http request for sending a message to a chat.
- close https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/1381
> Do you have any relevant URLs or Wiki pages that could …
=> add sendmessage handler function implementation

backend/ASTU-backend-group-4/internal/http/gin/chat.go
- implemented the function that handles an http request for generating a title for a chat.
- close https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/1427
> Do you have any relevant URLs or Wiki pages that …
=> add generatechattitle handler function implementation

backend/AASTU-backend-group-8/delivery/controllers/blog_handler.go, backend/AASTU-backend-group-8/delivery/routers/router.go, backend/AASTU-backend-group-8/domain/blog.go, backend/AASTU-backend-group-8/domain/misc.go, backend/AASTU-backend-group-8/repository/blog_repository.go, backend/AASTU-backend-group-8/usecases/blogusecase.go
=> Aastu.backend.g8.abenezer.filterandsearch

backend/ASTU-backend-group-4/internal/http/gin/chat.go
- implemented the function that handles an http request for deleting a chat.
- close https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/1434
> Do you have any relevant URLs or Wiki pages that could help give …
=> add delete-chat handler function implementation

backend/AAiT-backend-group-10/delivery/main.go, backend/AAiT-backend-group-10/delivery/router/router.go, backend/AAiT-backend-group-10/domain/customError.go, backend/AAiT-backend-group-10/go.mod, backend/AAiT-backend-group-10/go.sum, backend/AAiT-backend-group-10/infrastructures/cache_repo.go, backend/AAiT-backend-group-10/usecases/interfaces/cache_repo_interface.go
Created the caching repo and interface files
=> Aait.backend.g10.caching

backend/AASTU-backend-group-9/repository/comment_repository.go
=> :fire: update

backend/ASTU-backend-group-2/api/controller/profile_controller.go, backend/ASTU-backend-group-2/api/route/profile_route.go, backend/ASTU-backend-group-2/domain/user.go
**Overview:**
This PR adds the backend implementation for the "Change Password" feature. The following components have been developed:
1. **Authenticated Endpoint:** Introduced a new API endpoint that requires the user to be authenticated to access the password change functionality.
2. **Current Password Verification:** Added a step to verify the user's current password before allowing the update to a new password.
3. **Password Update Logic:** Implemented the logic to securely update the user's password in the database.
4. **Security Measures:** Ensured the entire process is secure, with proper validation and protection against common vulnerabilities.
=> feat: :sparkles: add change password functioality

backend/AAiT-backend-group-11/delivery/controller/auth_controller.go, backend/AAiT-backend-group-11/delivery/controller/profile_controller.go, backend/AAiT-backend-group-11/delivery/router/auth_router.go, backend/AAiT-backend-group-11/delivery/router/profile_router.go, backend/AAiT-backend-group-11/domain/dto/profile_dto.go, backend/AAiT-backend-group-11/domain/interfaces/profile.go, backend/AAiT-backend-group-11/go.mod, backend/AAiT-backend-group-11/go.sum, backend/AAiT-backend-group-11/infrastructure/middleware/authorization.go, backend/AAiT-backend-group-11/repository/profile_repository.go, backend/AAiT-backend-group-11/service/auth_serivce.go, backend/AAiT-backend-group-11/service/profile_service.go, backend/AAiT-backend-group-11/service/token_service.go, backend/AAiT-backend-group-11/utils/password_service.go
key changes;
- Use Dto to create and update user profile
- update profile service methods
- add a code to check if the user is deleting and updating their own profile
- allow profile view for all
=> update profile service and controller

backend/AAiT-backend-group-2/Delivery/routers/blog_router.go, backend/AAiT-backend-group-2/Domain/cache.go, backend/AAiT-backend-group-2/Domain/config.go, backend/AAiT-backend-group-2/Infrastructure/cache/redis_caching.go, backend/AAiT-backend-group-2/Repositories/blog_repository.go, backend/AAiT-backend-group-2/go.mod, backend/AAiT-backend-group-2/go.sum
Aait.backend.g2.mentesnot.caching_for_crud
=> Aait.backend.g2.mentesnot.caching_for_crud

backend/ASTU-backend-group-4/blog/blog.go, backend/ASTU-backend-group-4/blog/usecase.go, backend/ASTU-backend-group-4/internal/http/gin/blog.go
- implemented the function that handles all http request for the usecases.
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/1387
> Do you have any relevant URLs or Wiki pages that could help give background …
=> feat(blog): finished implementing the controllers

backend/ASTU-backend-group-4/auth/usecase.go, backend/ASTU-backend-group-4/internal/http/gin/auth.go
Implementation of authentication controllers, essential for managing user authentication and authorization within the application. This includes the following handlers:
- `UserRegistration`: Allows new users to register.
- `Login`: Authenticates users and issues JWT tokens.
- `UpdateProfile`: Enables users to update their profile information.
-  `Logout`: Handles user logout by invalidating tokens.
- Secure User Authentication: Establishes the foundation for secure user login and session management.
- User Account Management: Adds functionality for user registration and profile updates.
- Scalable Session Handling: Introduces JWT-based …
=> Start Implementing Auth Controllers

web/ASTU-web-group-2/banking-dashboard/.gitignore, web/ASTU-web-group-2/banking-dashboard/app/page.tsx
=> adding home page

backend/ASTU-backend-group-4/internal/http/gin/middleware.go
> Do you have any relevant URLs or Wiki pages that could help give background information for the changes in this Pull-Request? These are usually StackOverflow posts, Notion wiki pages, Wikipedia articles, or links to APIs and …
=> finish the implementation of auth middleware

mobile/AASTU-mobile-group-5/Maki.md
=> :memo: hate you dani

backend/AAiT-backend-group-13/cmd/main.go
Changes
Bug Fix: Corrected the conversion and usage of time.Duration to ensure accurate time calculations.
Refactor Code: Simplified the duration handling by ensuring consistency in how durations are set and compared.
Update Logic: Adjusted logic in the scheduling and expiration functionalities to properly use time.Duration values.
Test Coverage: Enhanced unit tests to cover scenarios involving time.Duration and verify the correct handling of time-based operations.
@beka-birhanu 
@Efamamo
=> fix: fix time casting in mail

backend/AASTU-backend-group-9/README.md, backend/AASTU-backend-group-9/docs/docs.md
=> Aastu.backend.g9.hiwot.documentation

mobile/AASTU-mobile-group-5/pubspec.lock, mobile/AASTU-mobile-group-5/pubspec.yaml
=> :arrow_up: Upgrade dependencies

mobile/AASTU-mobile-group-5/pubspec.lock
=> aastu.mobile.g5.app_bar

mobile/AASTU-mobile-group-6/pubspec.lock
created the folder structure
@nina17arse
=> folder structure

backend/AAiT-backend-group-13/cmd/main.go, backend/AAiT-backend-group-13/infrastructure/repo/blog/repo.go, backend/AAiT-backend-group-13/usecase/ai_recommendation/query/gemini_query.go
=> blog delete fixed

mobile/AASTU-mobile-group-5/android/app/build.gradle, mobile/AASTU-mobile-group-5/lib/features/chat/presentation/widgets/bottom_nav_bar/bottom_nav_bar.dart, mobile/AASTU-mobile-group-5/lib/features/chat/presentation/widgets/bottom_nav_bar/file_picker_widget.dart, mobile/AASTU-mobile-group-5/lib/features/chat/presentation/widgets/bottom_nav_bar/image_capture_widget.dart, mobile/AASTU-mobile-group-5/lib/features/chat/presentation/widgets/bottom_nav_bar/voice_recording_widget.dart, mobile/AASTU-mobile-group-5/lib/main.dart, mobile/AASTU-mobile-group-5/pubspec.lock
I did the nav bar but can't test it
=> :bottom: bottom nav bar started

backend/AAiT-backend-group-1/domain/infrastructure_interfaces.go, backend/AAiT-backend-group-1/domain/usecase_interfaces.go, backend/AAiT-backend-group-1/infrastructure/mail/mail_service.go, backend/AAiT-backend-group-1/usecases/user_usecase.go
modified the reset code option for the password reset email
=> the reset code added

backend/AAiT-backend-group-10/delivery/router/router.go, backend/AAiT-backend-group-10/infrastructures/cache_repo.go, backend/AAiT-backend-group-10/repositories/like.go, backend/AAiT-backend-group-10/usecases/comment.go, backend/AAiT-backend-group-10/usecases/interfaces/cache_repo_interface.go, backend/AAiT-backend-group-10/usecases/interfaces/like_repo_interface.go, backend/AAiT-backend-group-10/usecases/like.go
Added caching to like and comment
=> Aait.backend.g10.samrawit.caching

web/AAiT-web-group-7/bankdash/app/(directories)/transactions/page.tsx, web/AAiT-web-group-7/bankdash/components/commonalities/BalanceCard.tsx, web/AAiT-web-group-7/bankdash/components/transactions/ExpenseChart.tsx, web/AAiT-web-group-7/bankdash/components/transactions/Pagenation.tsx, web/AAiT-web-group-7/bankdash/components/transactions/Transactions.tsx, web/AAiT-web-group-7/bankdash/package-lock.json
Transactions component will be refactored after we know the form of the data we get from the API.Also, the card for the expense chart is I bit larger because you made the other cards smaller.
=> Aait.web.g7.zemenumain

mobile/AASTU-mobile-group-5/pubspec.lock
Implemented the chat page app_bar ui
=> chat_app_bar_ui_implemented

mobile/AASTU-mobile-group-5/lib/features/chat/presentation/widgets/profileWidget.dart, mobile/AASTU-mobile-group-5/lib/main.dart
=> Aastu.mobile.g5.maki.profile widget

backend/AAiT-backend-group-10/delivery/router/router.go, backend/AAiT-backend-group-10/infrastructures/cache_repo.go, backend/AAiT-backend-group-10/repositories/like.go, backend/AAiT-backend-group-10/usecases/blog.go, backend/AAiT-backend-group-10/usecases/comment.go, backend/AAiT-backend-group-10/usecases/dto/blog.go, backend/AAiT-backend-group-10/usecases/interfaces/cache_repo_interface.go, backend/AAiT-backend-group-10/usecases/interfaces/like_repo_interface.go, backend/AAiT-backend-group-10/usecases/like.go
Integrated caching using redis for blog requests
=> Aait.backend.g10.abenezer.blog caching

backend/AAiT-backend-group-11/delivery/router/auth_router.go, backend/AAiT-backend-group-11/domain/dto/comment_dto.go, backend/AAiT-backend-group-11/infrastructure/middleware/authorization.go, backend/AAiT-backend-group-11/repository/profile_repository.go
include some changes on the profile and auth service and repository
=> update profile and auth api

mobile/AASTU-mobile-group-5/lib/features/chat/presentation/pages/chat_display_people.dart, mobile/AASTU-mobile-group-5/lib/features/chat/presentation/pages/chat_test_page.dart, mobile/AASTU-mobile-group-5/lib/features/chat/presentation/widgets/avatar_with_name.dart, mobile/AASTU-mobile-group-5/lib/features/chat/presentation/widgets/profile_widget.dart, mobile/AASTU-mobile-group-5/lib/features/chat/presentation/widgets/user_conversation_widget.dart, mobile/AASTU-mobile-group-5/pubspec.lock
=> update profile widget

backend/ASTU-backend-group-4/chat/chat.go, backend/ASTU-backend-group-4/chat/usecase.go, backend/ASTU-backend-group-4/internal/http/gin/chat.go
- make the send-message usecase to generate title for a chat, if the message is the first one to the chat
- update the chat's title
- [close https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/1434](https://githu …
=> make the send-message usecase to generate title for a chat

backend/AAiT-backend-group-10/docs/api_documentation.md, backend/AAiT-backend-group-10/usecases/like.go
Added API documentation
fixed some bugs on like usecase
=> Added documentation and fixed a bug on like usecase

backend/ASTU-backend-group-4/chat/gemini_ai/ai-service.go
- remove the unnecessary prompt parameters from the AIService constructor
- [close https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/1434](https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/i …
=> fix(chat): update the parameter of the AIService constructor

mobile/AASTU-mobile-group-3/ecommerse_collab/lib/features/chat/presentation/widgets/text_inputter.dart, mobile/AASTU-mobile-group-3/ecommerse_collab/pubspec.lock
added text writer widget for the chat page
=> text writer widget

web/AASTU-web-group-2/a2sv-banking-system/app/creditCards/PieChart.tsx, web/AASTU-web-group-2/a2sv-banking-system/app/creditCards/page.tsx, web/AASTU-web-group-2/a2sv-banking-system/lib/api/companyControl.ts, web/AASTU-web-group-2/a2sv-banking-system/lib/api/userControl.ts
=> Aastu.web.g2.mahfouz.cards backend

web/AAiT-web-group-6/aai-web-group-6/src/app/dashboard/settings/page.tsx, web/AAiT-web-group-6/aai-web-group-6/src/components/settings/EditProfile.tsx, web/AAiT-web-group-6/aai-web-group-6/src/components/settings/SettingWhole.tsx
=> Settings Page Unresponsive

mobile/AAiT-mobile-group-2/ecom_app/lib/features/chat/mockData/mock_chat_data.dart, mobile/AAiT-mobile-group-2/ecom_app/lib/features/chat/presentation/pages/individual_chat_page.dart
chore: refactored the individual chat page
=> chore: refactored chat page

mobile/AASTU-mobile-group-5/lib/features/chat/domain/use_case/delete_chat.dart
=> :adhesive_bandage: delete it!

backend/ASTU-backend-group-2/api/controller/refresh_token_controller.go, backend/ASTU-backend-group-2/api/route/auth_route.go, backend/ASTU-backend-group-2/internal/tokenutil/tokenutil.go
**Description:**
This PR updates the `IsAuthorized` function to include checks for token expiry. With this enhancement, the function will now verify both the validity and the expiration of tokens, improving the security of our authentication system.
**Changes Made:**
- **Modified `IsAuthorized` Function:** Added logic to check the expiry date of tokens using `jwt.RegisteredClaims`.
**Details:**
- The function now parses the token and extracts the `ExpiresAt` claim.
- It checks whether the current time is past the token’s expiration time.
- If the token has expired, the function returns an appropriate error.
=> Astu.backend.g2.saleamlak.fix reset password and authentication issues

mobile/AASTU-mobile-group-5/lib/features/chat/domain/use_case/initiate_chat.dart, mobile/AASTU-mobile-group-5/lib/features/chat/presentation/widgets/profile_widget.dart
done the usecase initalize chat.
=> :tada: usecase done

backend/AASTU-backend-group-6/Delivery/controllers/blog_controller.go, backend/AASTU-backend-group-6/Domain/blog_domain.go, backend/AASTU-backend-group-6/Domain/user_domain.go, backend/AASTU-backend-group-6/Repositories/blog_repositories.go, backend/AASTU-backend-group-6/Usecases/blog_usecase.go, backend/AASTU-backend-group-6/Utils/make_primitive_list.go
Remove tole from the claims and update functions that require role
=> Use the commit before this one as a fallback.

mobile/AASTU-mobile-group-6/lib/features/product/presentation/pages/HomeChat.dart, mobile/AASTU-mobile-group-6/lib/main.dart, mobile/AASTU-mobile-group-6/pubspec.lock, mobile/AASTU-mobile-group-6/pubspec.yaml
=> Homepage for chat added

mobile/AASTU-mobile-group-5/lib/features/chat/data/models/chat_model.dart
=> chat model :sparkles:

web/ASTU-web-group-2/banking-dashboard/app/components/signIn/SignIn.tsx, web/ASTU-web-group-2/banking-dashboard/app/login/page.tsx, web/ASTU-web-group-2/banking-dashboard/cypress.config.ts, web/ASTU-web-group-2/banking-dashboard/cypress/e2e/demo.cy.ts, web/ASTU-web-group-2/banking-dashboard/cypress/fixtures/example.json, web/ASTU-web-group-2/banking-dashboard/cypress/support/commands.ts, web/ASTU-web-group-2/banking-dashboard/cypress/support/e2e.ts, web/ASTU-web-group-2/banking-dashboard/cypress/support/index.d.ts, web/ASTU-web-group-2/banking-dashboard/package-lock.json, web/ASTU-web-group-2/banking-dashboard/package.json
=> setting up cypress

web/AASTU-web-group-2/a2sv-banking-system/app/loans/components/Card1.tsx, web/AASTU-web-group-2/a2sv-banking-system/app/loans/page.tsx
=> loans dark mode

mobile/AASTU-mobile-group-6/lib/features/product/presentation/bloc/home_bloc.dart, mobile/AASTU-mobile-group-6/lib/features/product/presentation/bloc/home_event.dart, mobile/AASTU-mobile-group-6/lib/features/product/presentation/bloc/search/search_bloc.dart, mobile/AASTU-mobile-group-6/lib/features/product/presentation/bloc/search/search_event.dart, mobile/AASTU-mobile-group-6/lib/features/product/presentation/bloc/search/search_state.dart, mobile/AASTU-mobile-group-6/lib/features/product/presentation/pages/details.dart, mobile/AASTU-mobile-group-6/lib/features/product/presentation/pages/search.dart, mobile/AASTU-mobile-group-6/lib/locator.dart, mobile/AASTU-mobile-group-6/lib/main.dart
=> fixing the pages

backend/ASTU-backend-group-4/chat/usecase.go
- updated the usecase.createChat method to add a prompt engineered model response as the first message of the new chat.
- https://github.com/RealEskalate/a2sv-g5-project-phase-starter-project/issues/1741
> Do you have any relevant URLs …
=> add model response as the first message for new chats

mobile/AAiT-mobile-group-5/starter_project/lib/features/authentication/presentation/pages/sign_in.dart, mobile/AAiT-mobile-group-5/starter_project/lib/features/authentication/presentation/pages/sign_up.dart, mobile/AAiT-mobile-group-5/starter_project/lib/features/authentication/presentation/pages/terms_and_policy.dart, mobile/AAiT-mobile-group-5/starter_project/lib/features/authentication/presentation/widgets/authentication_text_field.dart, mobile/AAiT-mobile-group-5/starter_project/lib/features/authentication/presentation/widgets/ecom.dart, mobile/AAiT-mobile-group-5/starter_project/lib/features/authentication/presentation/widgets/redirect.dart, mobile/AAiT-mobile-group-5/starter_project/lib/main.dart, mobile/AAiT-mobile-group-5/starter_project/macos/Flutter/GeneratedPluginRegistrant.swift, mobile/AAiT-mobile-group-5/starter_project/pubspec.lock, mobile/AAiT-mobile-group-5/starter_project/pubspec.yaml
This pull request introduces the initial implementation of the authentication pages , specifically the Login and Signup pages. These pages provide the UI for user authentication features.
Changes Included
Login Page:
UI for user login, including input fields for email/username and password.
Button for submitting login credentials.
Navigation link to the Signup page for users without an account.
Signup Page:
UI for user registration, including input fields for username, email, and password.
Button for submitting signup details.
Navigation link to the Login page for existing users.
=> Aait.mobile.g5.michael.authentication.pages

web/AASTU-web-group-5/aastu.web.g5.bank-dashboard/app/Accounts/ChartCard.tsx, web/AASTU-web-group-5/aastu.web.g5.bank-dashboard/app/Accounts/page.tsx, web/AASTU-web-group-5/aastu.web.g5.bank-dashboard/app/Dashboard/components/BarchartComponent.tsx, web/AASTU-web-group-5/aastu.web.g5.bank-dashboard/app/Transaction/page.tsx, web/AASTU-web-group-5/aastu.web.g5.bank-dashboard/app/auth/signin/page.tsx, web/AASTU-web-group-5/aastu.web.g5.bank-dashboard/app/components/common/navBar.tsx, web/AASTU-web-group-5/aastu.web.g5.bank-dashboard/app/login/page.tsx
=> Aastu.web.g5.melkamu.fix errors
